# schema的中文医学信息抽取数据集CMeIE（Chinese Medical Information Extraction）
# CMeIE_CONFIG = {
#     "预防": 0,
#     "阶段": 1,
#     "就诊科室": 2,
#     "辅助治疗": 3,
#     "化疗": 4,
#     "放射治疗": 5,
#     "手术治疗": 6,
#     "实验室检查": 7,
#     "影像学检查": 8,
#     "辅助检查": 9,
#     "组织学检查": 10,
#     "内窥镜检查": 11,
#     "筛查": 12,
#     "多发群体": 13,
#     "发病率": 14,
#     "发病年龄": 15,
#     "多发地区": 16,
#     "发病性别倾向": 17,
#     "死亡率": 18,
#     "多发季节": 19,
#     "传播途径": 20,
#     "并发症": 21,
#     "病理分型": 22,
#     "相关（导致）": 23,
#     "鉴别诊断": 24,
#     "相关（转化）": 25,
#     "相关（症状）": 26,
#     "临床表现": 27,
#     "治疗后症状": 28,
#     "侵及周围组织转移的症状": 29,
#     "病因": 30,
#     "高危因素": 31,
#     "风险评估因素": 32,
#     "病史": 33,
#     "遗传因素": 34,
#     "发病机制": 35,
#     "病理生理": 36,
#     "药物治疗": 37,
#     "发病部位": 38,
#     "转移部位": 39,
#     "外侵部位": 40,
#     "预后状况": 41,
#     "预后生存率": 42,
#     "同义词": 43
# }
# CMeIE_CONFIG = {'实体组': 0, '否认': 1, '治疗施加于疾病': 2, '检查证实了疾病': 3, '持续': 4, '严重程度': 5, '可能的': 6, '非患者本人的': 7, '既往': 8, '待证实的': 9, '为了证实疾病而采取检查': 10, '治疗改善了疾病': 11, '性质': 12, '位置': 13, '检查证实了症状': 14, '治疗施加于症状': 15, '疾病导致症状': 16, '因为症状而采取检查': 17, '频率': 18, '偶有': 19, '治疗改善了症状': 20, '治疗导致了症状': 21, '有条件的': 22, '否认的': 23}
# CMeIE_CONFIG = {"/business/company/founders": 1, "/people/person/place_of_birth": 2, "/people/deceased_person/place_of_death": 3, "/business/company_shareholder/major_shareholder_of": 4, "/people/ethnicity/people": 5, "/location/neighborhood/neighborhood_of": 6, "/sports/sports_team/location": 7, "/business/company/industry": 9, "/business/company/place_founded": 10, "/location/administrative_division/country": 11, "None": 0, "/sports/sports_team_location/teams": 12, "/people/person/nationality": 13, "/people/person/religion": 14, "/business/company/advisors": 15, "/people/person/ethnicity": 16, "/people/ethnicity/geographic_distribution": 17, "/business/person/company": 8, "/business/company/major_shareholders": 19, "/people/person/place_lived": 18, "/people/person/profession": 20, "/location/country/capital": 21, "/location/location/contains": 22, "/location/country/administrative_divisions": 23, "/people/person/children": 24}
CMeIE_CONFIG ={"/business/company/advisors": 0,
               "/business/company/founders": 1,
               "/business/company/industry": 2,
               "/business/company/major_shareholders": 3,
               "/business/company/place_founded": 4,
               "/business/company_shareholder/major_shareholder_of": 5,
               "/business/person/company": 6,
               "/location/administrative_division/country": 7,
               "/location/country/administrative_divisions": 8,
               "/location/country/capital": 9,
               "/location/location/contains": 10,"/location/neighborhood/neighborhood_of": 11,"/people/deceased_person/place_of_death": 12,"/people/ethnicity/geographic_distribution": 13,"/people/ethnicity/people": 14,"/people/person/children": 15,"/people/person/ethnicity": 16,"/people/person/nationality": 17,"/people/person/place_lived": 18,"/people/person/place_of_birth": 19,"/people/person/profession": 20,"/people/person/religion": 21,"/sports/sports_team/location": 22,"/sports/sports_team_location/teams": 23}

Ent_BIO = {
    'O': 0,
    'B': 1,
    'I': 2,
}
